Solution for issue #936
kolide/fleet pull request #2336
Opened 2020-10-21 21:44 UTC by noahtalerman

- Using componentDidUpdate() to check for currentPage change in setup registration form. Initially tried adding `autofocus` prop to the first `<InputFieldWithIcon />` on each page. As seen in AdminDetails page. Didn't work. I believe React only pays attention to `autofocus` when the <input> is re-rendered.

- Calling focus() on page's first input  when currentPage changes and is true. Using refs callback

- Delaying focus by 300ms using setTimeout because the `.user-registration__field-wrapper` has a transition duration of 300ms. Setting the inputs focus immediately creates a snapping movement and ruins the smooth transition.

Note: If using setTimeout isn't ideal, then another potential solution is to create an event to listen for the transition's completion.

2020-10-21 21:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/kolide/fleet?pullRequest=2336) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/kolide/fleet?pullRequest=2336) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/kolide/fleet?pullRequest=2336) it.</sub>

2020-10-21 23:41 UTC, zwass requested changes
Clever! Thank you for documenting the reason for the `setTimeout` usage. I was definitely wondering when I saw the diff before I read the PR description. Can you actually put a quick note into the code where that is used so that it's right there for folks to understand?

It seems like a totally sufficient solution given that this is a page a user only hits once (if ever since it can also be done via `fleetctl`).

2020-10-22 00:30 UTC, noahtalerman commented
Got it! Comments are added. That now makes sense that one would attempt to first understand the code in the diff before being presented with the PR description. And for someone who's in the code there will be no PR description.

Re to user only hitting page once if that, sweet!

2020-10-22 01:03 UTC, zwass approved these changes
Thanks for adding the comments!

2020-10-22 01:03 UTC, merged